name: fpl
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.18.x, 1.19.x]

    runs-on: ubuntu-latest

    name: Build

    env:
      GOPATH: /home/runner/go

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4.0.0
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3.4.0

      - name: Get dependencies
        run: |
          PATH=$(go env GOPATH)/bin:$PATH
          make install

      - name: Spellcheck
        run: |
          make spell-check

      - name: Lint
        run: |
          make lint

      - name: Vet
        run: |
          make vet

      - name: Security
        run: |
          make security

      - name: Build
        run: |
          make build

      - name: Test
        run: |
          make test
